export const pharmacies = [
  {
    _id: 'pharm1',
    name: 'Монос Эмийн Сан',
    branch: 'Төв салбар',
    location: { type: 'Point', coordinates: [106.9057, 47.9077] },
    address: 'УБ хот, СБД, Энхтайваны өргөн чөлөө 15',
    phone: '9911-1234',
    workingHours: '08:00 – 22:00',
    isOpen: true,
    icon: '',
  },
  {
    _id: 'pharm2',
    name: 'Интер Эмийн Сан',
    branch: 'Баянзүрх салбар',
    location: { type: 'Point', coordinates: [107.0000, 47.9200] },
    address: 'УБ хот, БЗД, Их тойруу 10',
    phone: '9922-5678',
    workingHours: '09:00 – 21:00',
    isOpen: true,
    icon: '',
  },
  {
    _id: 'pharm3',
    name: 'Номин Эмийн Сан',
    branch: 'Хан-Уул салбар',
    location: { type: 'Point', coordinates: [106.8800, 47.8900] },
    address: 'УБ хот, ХУД, Зайсан 3',
    phone: '9933-9012',
    workingHours: '08:00 – 20:00',
    isOpen: false,
    icon: '',
  },
  {
    _id: 'pharm4',
    name: 'Диамед Эмийн Сан',
    branch: 'Сүхбаатар салбар',
    location: { type: 'Point', coordinates: [106.9200, 47.9150] },
    address: 'УБ хот, СБД, Бага тойруу 6',
    phone: '9944-3456',
    workingHours: '24 цаг',
    isOpen: true,
    icon: '',
  },
];

export const products = [
  {
    _id: 'pro1',
    name: 'Парацетамол',
    brand: 'Biomed',
    price: 2500,
    stock: 150,
    status: 'active',
    category: 'Өвчин намдаах',
    form: 'Таблет',
    symptoms: ['Толгой өвдөх', 'Халуурах', 'Биеийн өвдөлт'],
    description: 'Температур бууруулах болон өвдөлт намдаах зориулалтай эм.',
    usage: 'Насанд хүрэгчдэд 1–2 таблет, 4–6 цаг тутамд',
    ingredients: 'Paracetamol 500mg',
    warning: '3 хоногоос илүү хэрэглэхгүй. Элэгний өвчтэй хүмүүст болгоомжтой.',
    images: [],
    pharmacyId: 'pharm001',
  },
  {
    _id: 'pro2',
    name: 'Амоксициллин',
    brand: 'Sandoz',
    price: 8900,
    stock: 60,
    status: 'active',
    category: 'Антибиотик',
    form: 'Капсул',
    symptoms: ['Гэдэсний халдвар', 'Амьсгалын замын халдвар', 'Чихний үрэвсэл'],
    description: 'Бактерийн эсрэг өргөн хүрээний антибиотик.',
    usage: 'Эмчийн зааврын дагуу, ихэвчлэн 500мг × 3 удаа өдөрт',
    ingredients: 'Amoxicillin trihydrate 500mg',
    warning: 'Пенициллинд харшилтай хүмүүст хэрэглэхгүй.',
    images: [],
    pharmacyId: 'pharm1',
  },
  {
    _id: 'pro3',
    name: 'Ибупрофен',
    brand: 'Advil',
    price: 4200,
    stock: 0,
    status: 'out_of_stock',
    category: 'Үрэвсэл намдаах',
    form: 'Таблет',
    symptoms: ['Үе мөч өвдөх', 'Булчингийн өвдөлт', 'Халуурах'],
    description: 'Үрэвсэл болон өвдөлт намдаах, халуур бууруулах эм.',
    usage: '400–600мг, хоол идсэний дараа, 6–8 цаг тутамд',
    ingredients: 'Ibuprofen 400mg',
    warning: 'Ходоодны шархтай хүмүүст болгоомжтой хэрэглэх.',
    images: [],
    pharmacyId: 'pharm2',
  },
  {
    _id: 'pro4',
    name: 'Витамин С',
    brand: 'Pharmavit',
    price: 5500,
    stock: 200,
    status: 'active',
    category: 'Витамин',
    form: 'Шахмал',
    symptoms: ['Дархлаа суларсан', 'Ядаргаа', 'Ханиад'],
    description: 'Дархлааг бэхжүүлэх, чөлөөт радикалаас хамгаалах аскорбины хүчил.',
    usage: 'Өдөрт 1 шахмал, хоолны дараа',
    ingredients: 'Ascorbic acid 1000mg',
    warning: 'Хэт их тунгаар хэрэглэвэл ходоод дотор өвдөж болно.',
    images: [],
    pharmacyId: 'pharm3',
  },
  {
    _id: 'pro5',
    name: 'Омепразол',
    brand: 'Losec',
    price: 12000,
    stock: 45,
    status: 'active',
    category: 'Ходоодны эм',
    form: 'Капсул',
    symptoms: ['Ходоодны шарх', 'Хүчиллэг ихсэх', 'Гастрит'],
    description: 'Ходоодны хүчил үүсгэлийг бууруулдаг эм.',
    usage: 'Өдөрт нэг удаа, өглөө өлөн элгэн дээрээ',
    ingredients: 'Omeprazole 20mg',
    warning: 'Эмчийн зааврыг дагаж, 8 долоо хоногоос илүү хэрэглэхгүй байхыг зөвлөнө.',
    images: [],
    pharmacyId: 'pharm4',
  },
];
